const COLS=10,ROWS=20;
const boardEl=document.querySelector('#board'),nextEl=document.querySelector('#next'),overlay=document.querySelector('#overlay'),scoreEl=document.querySelector('#score'),linesEl=document.querySelector('#lines'),levelEl=document.querySelector('#level');
const newGameBtn=document.querySelector('#newGame'),startGameBtn=document.querySelector('#startGame');
const SHAPES={I:[[1,1,1,1]],O:[[1,1],[1,1]],T:[[0,1,0],[1,1,1]],S:[[0,1,1],[1,1,0]],Z:[[1,1,0],[0,1,1]],J:[[1,0,0],[1,1,1]],L:[[0,0,1],[1,1,1]]};
const TYPES=Object.keys(SHAPES);let grid=[],piece=null,nextType=null,score=0,lines=0,level=1,playing=false,paused=false,timer=null;
function empty(){return Array.from({length:ROWS},()=>Array(COLS).fill(null));}function clone(a){return a.map(r=>[...r]);}function rotate(m){return m[0].map((_,i)=>m.map(r=>r[i]).reverse());}function randomType(){return TYPES[Math.floor(Math.random()*TYPES.length)];}function newPiece(type){const shape=clone(SHAPES[type]);return{type,shape,x:Math.floor((COLS-shape[0].length)/2),y:0};}function collides(p,dx=0,dy=0,shape=p.shape){for(let y=0;y<shape.length;y++)for(let x=0;x<shape[y].length;x++)if(shape[y][x]){const nx=p.x+x+dx,ny=p.y+y+dy;if(nx<0||nx>=COLS||ny>=ROWS||(ny>=0&&grid[ny][nx]))return true;}return false;}
function merge(){piece.shape.forEach((r,y)=>r.forEach((v,x)=>{if(v&&piece.y+y>=0)grid[piece.y+y][piece.x+x]=piece.type;}));}function clearLines(){let n=0;grid=grid.filter(r=>{if(r.every(Boolean)){n++;return false;}return true;});while(grid.length<ROWS)grid.unshift(Array(COLS).fill(null));if(n){score+=([0,100,300,500,800][n]||1200)*level;lines+=n;level=Math.floor(lines/10)+1;resetTimer();}}function spawn(){piece=newPiece(nextType||randomType());nextType=randomType();if(collides(piece)){gameOver();return;}drawNext();}function drop(){if(!playing||paused)return;if(!collides(piece,0,1)){piece.y++;draw();return;}merge();clearLines();spawn();draw();}function hardDrop(){if(!playing||paused)return;let d=0;while(!collides(piece,0,1)){piece.y++;d++;}score+=d*2;merge();clearLines();spawn();draw();}function move(dx){if(!playing||paused)return;if(!collides(piece,dx,0)){piece.x+=dx;draw();}}function turn(){if(!playing||paused)return;const r=rotate(piece.shape);for(const dx of [0,-1,1,-2,2])if(!collides(piece,dx,0,r)){piece.x+=dx;piece.shape=r;draw();return;}}function resetTimer(){clearInterval(timer);timer=setInterval(drop,Math.max(90,800-(level-1)*65));}
function start(){grid=empty();score=0;lines=0;level=1;playing=true;paused=false;nextType=randomType();spawn();overlay.classList.add('hidden');resetTimer();draw();}
function gameOver(){playing=false;clearInterval(timer);overlay.innerHTML='<h2>GAME OVER</h2><p>NEW GAME을 눌러 다시 시작</p><button id="restartGame" class="start-btn" type="button">RESTART</button>';overlay.classList.remove('hidden');bindActionButton(document.querySelector('#restartGame'),start);}
function togglePause(){if(!playing)return;paused=!paused;if(paused){overlay.innerHTML='<h2>PAUSED</h2><p>계속하려면 RESUME</p><button id="resumeGame" class="start-btn" type="button">RESUME</button>';overlay.classList.remove('hidden');bindActionButton(document.querySelector('#resumeGame'),togglePause);}else overlay.classList.add('hidden');}
function update(){scoreEl.textContent=score;linesEl.textContent=lines;levelEl.textContent=level;}
function draw(){boardEl.innerHTML='';for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){const c=document.createElement('div');c.className='cell'+(grid[y][x]?' filled '+grid[y][x].toLowerCase():'');boardEl.appendChild(c);}if(piece)for(let y=0;y<piece.shape.length;y++)for(let x=0;x<piece.shape[y].length;x++)if(piece.shape[y][x]){const yy=piece.y+y,xx=piece.x+x;if(yy>=0){const c=boardEl.children[yy*COLS+xx];if(c)c.className='cell filled '+piece.type.toLowerCase();}}update();}
function drawNext(){nextEl.innerHTML='';const s=SHAPES[nextType];for(let y=0;y<4;y++)for(let x=0;x<4;x++){const c=document.createElement('div');c.className='cell';if(s?.[y]?.[x])c.className+=' filled '+nextType.toLowerCase();nextEl.appendChild(c);}}
function action(a){if(a==='left')move(-1);else if(a==='right')move(1);else if(a==='rotate')turn();else if(a==='down')drop();else if(a==='drop')hardDrop();}
function bindActionButton(button,fn){if(!button)return;let lastTouch=0;button.addEventListener('touchstart',e=>{e.preventDefault();e.stopPropagation();lastTouch=Date.now();fn();},{passive:false});button.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(Date.now()-lastTouch>450)fn();});}
newGameBtn?.addEventListener('click',start);startGameBtn?.addEventListener('click',start);
document.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowDown','ArrowUp',' '].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')action('left');else if(e.key==='ArrowRight')action('right');else if(e.key==='ArrowDown')action('down');else if(e.key==='ArrowUp')action('rotate');else if(e.key===' ')action('drop');else if(e.key.toLowerCase()==='p')togglePause();else if(e.key==='Enter'&&!playing)start();});
document.querySelectorAll('.mobile-controls button').forEach(button=>bindActionButton(button,()=>action(button.dataset.action)));
drawNext();draw();